### ISSUE TITLE
I'm sorry but what the f**k is this?

### ISSUE THREAD

**Issue by Mijyuoon** [jonschlinkert/is-whitespace#5]
What's the point of this thing even? It doesn't even contain the actual regexp used for testing, all it does is just calls `test()` on the regexp taken from another stupid dependency. I don't even… 🤦

**Comment by Earu** [comment]
The need to create another package showed up I guess... https://github.com/jonschlinkert/is-whitespace/commit/a0c31098b5ad804036e25c11bf708b8524203eb6
